### PR TITLE
Specify the command to create the default conf file

### PR DESCRIPTION
**Pull request by Dinduks**
Hi,
I hope _/etc/i3blocks.conf_ is the right path in all systems. :)

### CODE REVIEW

**Comment by Zopieux** [comment]
Well, to be fair `/etc/` files should be reserved for actual system programs/daemons. *Examples* of config files are usually stored under `/usr/share/doc/<progname>` or just `/usr/share/<progname>`.

**Comment by Dinduks** [comment]
I agree, the scripts are already stored in */usr/share/i3blocks/*. 
My patch only follows the actual state of things.

**Comment by tsaber** [comment]
bash: cd: /usr/share/i3blocks/: No such file or directory

**Comment by Zopieux** [comment]
By default (as configured in the [Makefile](https://github.com/vivien/i3blocks/blob/master/Makefile)), i3block scripts are stored in `/usr/libexec/i3blocks`.

**Comment by Dinduks** [comment]
I don't have a /usr/libexec directory (@ Debian Jessie).

**Comment by Zopieux** [comment]
Yep, that's distribution dependent. For Debian, it's `/usr/share/i3blocks` as per [the package file listing](https://packages.debian.org/jessie/amd64/i3blocks/filelist).

**Comment by Dinduks** [comment]
There's no .i3blocks.conf in /usr/share/i3blocks though.

**Comment by Zopieux** [comment]
The default `i3blocks.conf` **is** in `/etc`, and is used as a fallback when user has no custom conf in its home directory. I don't know how common of a practice this is, as `/etc` is usually for system wide service config.

**Comment by Dinduks** [comment]
And that's the one I suggest to copy to the user's directory. So my PR is good, isn't it?

**Comment by Nycroth** [comment]
Yep, that's correct. :+1:

**Comment by vivien** [comment]
The documentation will be completely reworked so I'll skip this for the moment!

**Pull request closed without merging**
