### PR TITLE
add kubernetes cluster and namespace

### PR DESCRIPTION
**Pull request by dbenque**
Display kubernetes active context and namespace

### CODE REVIEW

**Comment by jolange** [comment]
The right place for this would be https://github.com/vivien/i3blocks-contrib. Make sure to read `CONTRIBUTING.md`

**Comment by dbenque** [comment]
Ok... sorry but I don't find the CONTRIBUTING.md file. Can you post the link?
As suggested by your comment I will move my block in the i3blocks-contrib folder.

**Comment by jolange** [comment]
Sure: [CONTRIBUTING.md](https://github.com/vivien/i3blocks-contrib/blob/master/CONTRIBUTING.md)

**Comment by dbenque** [comment]
https://github.com/vivien/i3blocks-contrib/pull/125

**Pull request closed without merging**
