### PR TITLE
Manually merge @Airblader's patch

### PR DESCRIPTION
**Pull request by kgilmer**
Ref: https://github.com/vivien/i3blocks/issues/198 and add lib dependencies.

@vivien I'm guessing you are not interested in taking this change but am creating this PR in case you do or have any interest in the change.
@Airblader, my cave-man C skills are not seeing any inefficiencies here.  The only thing that comes to mind is not recreating the xcb connection each time a resource is found.  Any hints as to what needs to be optimized?  I did a quick test and verified that the resource literals are resolved as expected.

### CODE REVIEW

**Comment by kgilmer** [comment]
Related to https://github.com/regolith-linux/regolith-desktop/issues/24

**Comment by Airblader** [comment]
Yeah, the connection get created every time and, almost worse, the resource database is loaded again every time. That's just really unnecessary and all of that should just happen once when i3blocks starts up.

**Comment by kgilmer** [comment]
Related to https://github.com/vivien/i3blocks/issues/198

**Comment by kgilmer** [comment]
I think I've fixed the Xresource db being loaded multiple times.  The downside is that it's always loaded, even if no Xresources are referenced.  I personally don't find this to be a concern but maybe I'm ignorant of something.

**Comment by kgilmer** [comment]
Hmm, when I test this locally it seems to break i3blocks, but the previous version does not.  I'll need to do some more debugging.

**Comment by kgilmer** [comment]
Since it doesn't seem that the project maintainer is interested in this change (by lack of response) I forked this and called it 'i3xrocks'.  I'm not proud of the name.  I did my best to be respectful of the upstream author and am not intending to impersonate or otherwise cause harm to the project, but if something looks wrong let me know and I'll fix it.

https://github.com/regolith-linux/i3xrocks

**Comment by Airblader** [comment]
I think you should give him more than two days to respond. ;-)

**Comment by kgilmer** [comment]
Sure, you're right.  Sometimes I forget to leave the day job at the office.

**Comment by gportay** [comment]
Hi @kgilmer, I am using *i3block* on *sway* (ie. Wayland), and thus those changes will break things for me (at least in the current state).

Thus, you should wrap around the code with `#if HAVE_XRESOURCES ... #endif` and add `--enable-xresources` or whatever the name option in the `configure.ac`.

IIUC if a value of a variable from the config file starts with `resource:`, the value is then replaced by the value from the `.Xresources` database.

I prefer to use prefix `xresources:` to be more specific.

Furthermore, I am not fond of that because it forces all variables that starts with `resource:` to be replaced. Maybe some values have a good reason to starts with that prefix and should no be replaced then.

Even with that, I would prefer i3blocks to not hardcode X things in i3blocks. I would like it to stay agnostic from X or Wayland. If not, it should probably have the same thing for Wayland, and then for the successor of Wayland, and so on...

In the end, I suggest to write a wrapper in bash for *i3blocks* instead. Its goal is to export the X resources variables you need for all of you blocklets.

This solution have the advantage of avoiding you to maintain a fork that is something you do not want to do; in case of the PR is not merged in *i3blocks*.

But maybe I missed something. If so, do not hesitate to yell at me :p

``` bash
#!/bin/bash
#
# Xblocks - i3blocks wrapper for X
#

mapfile -t xresources < <(xrdb -query)

for xresource in "${xresources[@]}"
do
	read val value < <(echo "${xresource/:	/ }")
	if [[ "$var" =~ ^(bad_color|good_color|)$ ]] # Filter here if needed.
	then
		continue;
	fi
	eval 'export ${val//./_}="$value"' # Sanitizie the $var
done

exec i3blocks "$@" 
```

Nitpick: take care to the indentation. The project uses tabs, not spaces.

**Comment by kgilmer** [comment]
Hi @gportay !

Thank you for your detailed and thoughtful feedback on the PR.

> I am using i3block on sway..
Ah, I didn't realize i3blocks was used on Wayland.  Yes this would be a problem and would need to be hidden behind some ifdefs, thanks for the suggestion.

> I prefer to use prefix xresources: to be more specific.
+1

>Furthermore, I am not fond of that because it forces all variables that starts with resource: to be replaced. Maybe some values have a good reason to starts with that prefix and should no be replaced then.
I'm guessing this would be especially rare, while possible.  Especially if the prefix is `Xresource:`

Regarding the bash shell script, thank you for providing that!  I had to play around with it a bit to understand how it works.  (_note to self, remove Bash from resume_.)  In essence it's transforming Xresources into environment variables, from which presumably i3blocks can resolve internally.  I didn't get this far as I ran into an issue; Xresources uses the `.` character to [partition keys into segments](https://en.wikipedia.org/wiki/X_resources), and has a specific schema for how resources should be defined.  Environment variables seem to be [rather constrained](https://stackoverflow.com/a/2821183/339434) in what characters they can use.  Period is not one of them:
```
$ export St.color12=3
bash: export: `St.color12=3': not a valid identifier
```

Nor is the `-` character or some other things I have in my Xresources legal as an environment key name.  One could strip or transform the illegal characters into something else, but then the user would have to understand these rules.  And in the case of stripping the characters there is the possibility of name collisions, while probably rare.

My motivation for this functionality in i3blocks (and other UI components used in Regolith) is to allow users the ability to theme their desktop by just modifying Xresource values.  If I require special rules per component, I do not feel that this meets my goal.  On the other hand, this solution saves me from a forked package.  Maybe there is a way to preserve the mapping that's not clear to me or I misunderstand a capability of your script?

**Comment by gportay** [comment]
> I'm guessing this would be especially rare, while possible. Especially if the prefix is `Xresource:`

Indeed.

> Regarding the bash shell script, thank you for providing that! I had to play around with it a bit to understand how it works. (_note to self, remove Bash from resume_.) In essence it's transforming Xresources into environment variables, from which presumably i3blocks can resolve internally. I didn't get this far as I ran into an issue; Xresources uses the `.` character to [partition keys into segments](https://en.wikipedia.org/wiki/X_resources), and has a specific schema for how resources should be defined. Environment variables seem to be [rather constrained](https://stackoverflow.com/a/2821183/339434) in what characters they can use. Period is not one of them:
> 
> ```
> $ export St.color12=3
> bash: export: `St.color12=3': not a valid identifier
> ```
> 
> Nor is the `-` character or some other things I have in my Xresources legal as an environment key name. One could strip or transform the illegal characters into something else, but then the user would have to understand these rules. And in the case of stripping the characters there is the possibility of name collisions, while probably rare.

It could be nice to have some real use-cases here. I mean to have examples with real Xresources keys that are actually used in Regolith. I assume `St.color12:	3` is a real example, right?

How you expect the blocklets to use the Xresources? Could you paste an example of the i3block.config and a simple blocklet script?

> ```shell
> 	eval 'export ${val//./_}="$value"' # Sanitizie the $var
> ```

This is the place where I want to 'sed' the character from the Xresources key that are not valid for a shell variable name (i.e. `-`, `*`, `.`....) and replace it by `_`.

**Comment by kgilmer** [comment]
> It could be nice to have some real use-cases here.

Real-world examples: https://github.com/regolith-linux/regolith-styles/tree/master/Xresources.  This is a "flattened" perspective on Xresources where each UI component associated directly with colors and other theme elements.  I expect there will be an additional layer (similar to how styles work in Android) which defines an abstract subset of colors.  This would allow users to change themes by mapping these abstract color definitions to colors and have them apply to all UI components.

> How you expect the blocklets to use the Xresources?

I am using `xgetres` in scripts to extract specific values from Xresource keys.  Here is a WIP example of `cpu_usage`:
```
#!/usr/bin/perl
#
# Copyright 2014 Pierre Mavro <deimos@deimos.fr>
# Copyright 2014 Vivien Didelot <vivien@didelot.org>
# Copyright 2014 Andreas Guldstrand <andreas.guldstrand@gmail.com>
#
# Licensed under the terms of the GNU GPL v3, or any later version.

use strict;
use warnings;
use utf8;
use Getopt::Long;

# default values
my $t_warn = 50;
my $t_crit = 80;
my $cpu_usage = -1;

sub help {
    print "Usage: cpu_usage [-w <warning>] [-c <critical>]\n";
    print "-w <percent>: warning threshold to become yellow\n";
    print "-c <percent>: critical threshold to become red\n";
    exit 0;
}

GetOptions("help|h" => \&help,
           "w=i"    => \$t_warn,
           "c=i"    => \$t_crit);

# Get CPU usage
$ENV{LC_ALL}="en_US"; # if mpstat is not run under en_US locale, things may break, so make sure it is
open (MPSTAT, 'mpstat 1 1 |') or die;
while (<MPSTAT>) {
    if (/^Average.*\s+(\d+\.\d+)/) {
        $cpu_usage = 100 - $1; # 100% - %idle
        last;
    }
}
close(MPSTAT);

$cpu_usage eq -1 and die 'Can\'t find CPU information';

# Print short_text, full_text
printf "<span font_desc='Source Code Pro Medium 13' color='%s'>%2d%%</span>\n", `xgetres i3blocks.value.color`, $cpu_usage;
printf "<span font_desc='Source Code Pro Medium 13' color='%s'>%2d%%</span>\n", `xgetres i3blocks.value.color`, $cpu_usage;

exit 0;
```

> This is the place where I want to 'sed' the character from the Xresources key that are not valid for a shell variable name (i.e. -, *, .....) and replace it by _.

Oh, I see!  I didn't recognize that when playing with the script last night but now I understand the intention.

**Comment by vivien** [comment]
Hi @kgilmer,

As mentioned in the referenced feature request, I do not wish to add such dependency to i3blocks, especially since it isn't limited to i3 or i3-gaps anymore. This project currently does not build against any library, so I would like to keep it like this if possible. Best of luck with i3xrocks!

**Pull request closed without merging**
