### PR TITLE
Notification when battery is critically low

### PR DESCRIPTION
**Pull request by veelenga**
Few times my laptop turned off due full discharging. Simple notification really helps.

But this implementation has one disadvantage. User will be notified few times before full discharging (number of times depends on period in config). To prevent this we can use perl's [Storable](http://perl.yaritz.com/perl_variables.html) (save information between script execution about have we notified or not, so only one notification will be displayed). But this solution is not very clear. Let me know if you think it's better...

### CODE REVIEW

**Comment by vivien** [comment]
Hi! While notifying the user is a good idea (this often happens to me too in fact!), some of them may not use libnotify, so I think this is not the good place. I think that urgency should be handled by higher i3 components, like i3bar or i3 itself. Maybe i3 allows to trigger a custom command when receiving an urgency. If not, it might be a good addition to propose to the maintainer. We need to dig that up! :)

**Comment by veelenga** [comment]
@vivien Hello. Yeah, you are correct, this is a bad place. Somebody do not use libnotify and somebody use something like gnome-settings-daemon and will be notified from two streams etc.

I didn't found clear solution for this with higher i3 components. Internet suggests custom bash scripts running via cron :) [1](https://faq.i3wm.org/question/1730/warning-popup-when-battery-very-low/), [2] (https://github.com/agribu/i3-battery-warning).

You may close request if do no plan to investigate. 

Regards.

**Comment by Nycroth** [comment]
Well, here's my two sense:
I'd say that, so long as the calls to libnotify gracefully (i.e. silently) handle it not being installed, this would class as an optional dependency.

However, I also agree with you @vivien, i3bar should be given the ability to handle urgency better. i3blocks shouldn't really be reinventing notifications. Currently, there is a [patch](http://cr.i3wm.org/patch/682) to highlight the field that is flagged as urgent. Unfortunately, this lacks libnotifiy integration as this will require a protocol change to include the ability to send a message. I'm not sure if anyone is willing to follow through with this by contacting the i3 dev team to talk about such a feature. I'm not at the moment but someone might be. I'd make this an issue to invite a volunteer to check this out (and remind any of us if we find time).

@veelenga, for now if you want to make a gist patch and include it in the wiki for adding notifications (using Storable) I'd encourage this approach. I'm not sure how to add an urgent flag in the battery script when the battery is critical (the exit 33 isn't the right approach). If you want to apply this change for when i3bar gets its update this would be as good an addition as is appropriate for now.

**Comment by veelenga** [comment]
@Nycroth Thanks. I'm going to investigate approach with i3bar patch. I will let you know.

**Comment by thiagowfx** [comment]
Hum, this feature is really interesting, but I have to agree that mixing it with i3blocks would create much complexity; its scripts should probably not be concerned with system notifications. In fact, I believe that battery should not have to do even with i3 itself. Cron, udev, systemd and bash scripts...one or more of those are probably better. 

The best that i3blocks can offer without creating much complexity is to change the color of this block to a very bright red when the battery is low, but this is implemented already. 20% is not super low, of course; maybe we could change those limits. Something like 10% could be red, for example.

**Comment by Nycroth** [comment]
@thiagowfx, I disagree that an information utility (i3blocks & i3bar) shouldn't handle notifications. In fact I counter that i3bar is exactly the X component to handle notifications. Of course cron, udev, systemd, or a bash daemon can all handle a battery notification but if a user desires resident monitoring (what i3blocks/i3bar provides) of their battery, the ability for the already existent monitor to push a notification to the system libnotify daemon is just a logical extension. It's no complexity at ass because we use the libnotify infrastructure. It's a single shell command. The only argument we had was that i3blocks should pass a notification to i3bar because a user may want to apply notification configuration such as formatting or aggregation that should be applied to all blocks wanting to notify the user. i3bar protocol already has an urgency flag for a block but until now has not utilized this in it's display. In essence, i3blocks is only a shell to i3bar protocol translator so we believe i3bar protocol should allow us to send it a message to warn or inform the user.

As for colour thresholds, anyone is free to change this to meet their needs (Bless the GPL). Something to remember though is that a lithium battery has a very unique [voltage profile](http://batteryuniversity.com/learn/article/lithium_based_batteries) that limits the controller's (and thus the computer's) ability to properly estimate the charge left. In this case, prudence is a means to prevent accidental power starvation (and possible resulting data loss). Often people feel their task will be quicker than the battery will discharge fully so they won't plug in, then they are caught off guard when they see that battery is critically low. The grade also starts far out (85%) to more slowly change the colour. Something that could be very cool would be a patch to grade it continuously from green to red by using an equation to manipulate the hex value from #FF00000 to #00FF00 where 100% is #FF00000 and `-t ##` or the default 10% or 15% is #00FF00. I think I'll add this actually. =D

Anyway, hope that helps clear some of the issues. Feel free to let me know what you think.

**Comment by thiagowfx** [comment]
I am not familiar with the capabilities of i3bar besides changing the program which feeds text into it, like i3blocks, i3status, etc. If its 'urgent' status  / flags provides some facilities to handle notifications, then just  go ahead :).

If notifications were to be implemented, I think that at least it should be done in a consistent way to all blocks.

But I am personally satisfied with your new patch (I haven't tested it, no battery here) for now.

**Comment by Nycroth** [comment]
Well that's where we're @veelenga is headed. Presently, i3bar protocol supports the urgent bool but does nothing with it. A patch is has been submitted (by others) to colour the background of that block with the urgent colour used by the workplace label when a window notifies urgency (bell/activity). What we would like to do is add an urgency message to the protocol and libnotify support to i3bar to allow it to inform the user why the bar has been marked urgent. Maybe even also provide the dismissal of the urgency.

**Pull request closed without merging**
