### PR TITLE
Expand regex to match new mpstat output format

### PR DESCRIPTION
**Pull request by kb100**
Fixes https://github.com/vivien/i3blocks/issues/251

### CODE REVIEW

**Comment by kb100** [comment]
I just noticed this. Sometimes acpi gives the following confusing output

    Battery 0: Charging, 100%,  until charged

resulting in the blocklet writing a confusing `(until)`

**Comment by jolange** [comment]
I guess that comment was meant to go to vivien/i3blocks-contrib#105

**Comment by 0x6d636c61757373** [comment]
I just had the same problem with the regex and sysstat version 11.5.7. I shortened and modified the regex to `/(\d+\.\d+).$/` and it works. I think the original regex is too long if you just want to have the entry in the last column. Note that `.` matches everything except `\n`, so this should work for `\s` and `\x00' (see https://perldoc.perl.org/perlre.html).

**Comment by AgamAgarwal** [comment]
I just had the same problem too and had to create a copy of the `cpu_usage` script with the fix for my use. Any plans on merging this PR?

**Comment by vivien** [comment]
Hi guys, we are in the process of moving all default scripts to i3blocks-contrib. Can you send this PR against https://github.com/vivien/i3blocks-contrib/tree/master/cpu_usage please? Thanks!

**Comment by kb100** [comment]
Merged in i3blocks-contrib many moons ago.

**Pull request closed without merging**
