### PR TITLE
Gaps

### PR DESCRIPTION
**Pull request by Airblader**

### CODE REVIEW

**Comment by Airblader** [comment]
Support for this will be removed again.

**Comment by Airblader** [comment]
@vivien Actually i3-gaps will keep support for this, so I'll reopen.

**Comment by vivien** [comment]
Hi @Airblader ! I don't really understand what this pull request is acheiving. Do you want me to rebase the i3blocks' gaps branch?

**Comment by Airblader** [comment]
It's a rebase, but also changes the length of color input from 8 to 10 to allow RGBA. :)

**Comment by Airblader** [comment]
There might be no need to merge this. I think that maybe I should just fork this to maintain the gaps branch and provide an AUR package for it. That'd be easier for the both of us.

**Comment by Airblader** [comment]
I am not maintaining my own fork and aur/i3blocks-gaps-git for this, so closing again. ;)

**Comment by vivien** [comment]
Indeed I won't merge a rebase ^^

I think maintaining a fork is for the moment a better option. But I can tell you that I have plans in mind to make i3blocks very generic, so new official or non-official i3bar properties won't be a problem anyway. Scripts will benefice from this too. I hardly find free time these days, but I keep this on top of my head. I'll let you know how things progress. Thanks!

**Pull request closed without merging**
