### PR TITLE
Little fix on `hostname` option for example

### PR DESCRIPTION
**Pull request by jjerphan**
Hi,
This is just a small fix for a typo on `hostname` option for one of the README.md example.
Thanks for maintaining `i3blocks`!

### CODE REVIEW

**Comment by vivien** [comment]
Hum that is weird, I don't have this `--all-ip-addresses` you're using:
````
$ hostname --all-ip-addresses
hostname: unrecognized option '--all-ip-addresses'
Try 'hostname --help' or 'hostname --usage' for more information.
````

**Comment by jjerphan** [comment]
Hum, this option is not available on `hostname 3.20` (Fedora 29, Ubuntu 18).
However `--ip-address` is on this version and may exist on yours too.

**Comment by vivien** [comment]
`--ip-address` is the same as `--ip-addresses` or `--ip-addr`.

**Comment by jjerphan** [comment]
OK, so what would you recommend choosing to be version agnostic?

**Comment by vivien** [comment]
Ho I misread your comment. You're saying that you have `--ip-address` but not `--ip-addresses`, correct?

If there's such different, let's just use the short version `-i` to avoid any confusion.

**Comment by jjerphan** [comment]
> Ho I misread your comment.

No problem. :)

> You're saying that you have --ip-address but not --ip-addresses, correct?

This is what I get from `man`:
```man
       -i, --ip-address
              Display the network address(es) of the host name. Note that this works only if the host name can be resolved. Avoid using this option; use hostname --all-ip-addresses instead.

       -I, --all-ip-addresses
              Display  all network addresses of the host. This option enumerates all configured addresses on all network interfaces. The loopback interface and IPv6 link-local addresses are omitted. Contrary
              to option -i, this option does not depend on name resolution. Do not make any assumptions about the order of the output.
```

On my version of `hostname`:
 - I don't have `--ip-addresses` as an option ;
 - `-i`, `--i` and `--ip`(maybe not exhaustive) triggers the first option (ie.  `--ip-address`) too, this is what you are giving what you are looking for ; 
 - `--all-ip-address`triggers the second option too. 


> If there's such different, let's just use the short version -i to avoid any confusion.
Yes!

**Comment by jjerphan** [comment]
Fixed. 👌

**Comment by vivien** [comment]
I've squashed this branch and reworded the commit a little. Thanks Julien!

**Comment by jjerphan** [comment]
You're welcome Vivien!

**Pull request closed without merging**
