### PR TITLE
Fix at amixer command

### PR DESCRIPTION
**Pull request by rainbowintheshell**
I found a bug. If volume is 100%, only show 00%. I fixed that regex.

### CODE REVIEW

**Comment by kb100** [comment]
The given regex does not work for 0% to 9%. Use `[0-9]{1,3}%` instead

**Comment by rainbowintheshell** [comment]
You are right kb100. Fixed.

**Comment by kb100** [comment]
As long as I'm looking at it, what does the `-E` flag do? I know the man page says extended regular expression but it seems to work without the flag. Also, I would prefer to use `-C1` to have grep stop looking after one match, instead of finding all matches and then discarding all but the first (piping to `head`).

**Comment by vivien** [comment]
@kb100 if I'm not mistaken, `-C` is the number of context lines, not the number of occurence. e.g. `-C 3` will also print the line before and after the occurence.

**Comment by vivien** [comment]
Thanks both of you!

**Comment by kb100** [comment]
Ahh, I was thinking of `-m1` not `-C1`

**Pull request closed without merging**
