### PR TITLE
Added click actions to "mediaplayer" script.

### PR DESCRIPTION
**Pull request by roobre**
You can now go to the previous track with left button, next track with right button, and play/pause with middle button.

### CODE REVIEW

**Comment by vivien** [comment]
I'd agree with this change. @acrisci may I ask your feedback on this change?
Also, (just curious) as left click might be misleading, wouldn't it be "safer" to use wheel up/down to switch tracks?

**Comment by roobre** [comment]
@vivien Well, I chose clicks mainly because I use i3 on my laptop, and the touchpad buttons are more accesible than the mouse wheel.

Also, if you happen to have the `mediaplayer` block next to the `volume` as I do, an small mouse misplacement would either skip tracks to infinite or change the volume.

**Comment by acrisci** [comment]
:+1:

**Comment by vivien** [comment]
Thanks

**Pull request closed without merging**
