### PR TITLE
Remove unsupported code for clang/freebsd

### PR DESCRIPTION
**Pull request by timello**
This shouldn't be the right way to go, removing possible features
but I'm unsure if the code is portable.

Please, advise.

### CODE REVIEW

**Comment by vivien** [comment]
Hum, such concerns have been raised by @jpleau. I will create a ticket for BSD support, to track this down. IIRC BSD does not support the realtime signals. I'll have to dig that up and find a BSD machine somehow...

**Comment by timello** [comment]
Hi,
If you accept as a suggestion ... you can install freeBSD very easily using VirtualBox or any other hypervisor. PC-BSD is also a option.

**Comment by vivien** [comment]
Indeed, I'll check this out! Thanks.

**Comment by timello** [comment]
I would be interested to maintain a port in freebsd if we can make it portable.

**Comment by timello** [comment]
Please, check this out... not sure if it is what you a re looking for: https://github.com/freebsd/freebsd/blob/master/sys/sys/signal.h#L117

**Comment by netzverweigerer** [comment]
Hello!

I don't know if it's of any help, but I just tried to build this on my FreeBSD notebook (X220, FreeBSD 10.3-STABLE). The output of gmake is attached:

cc -std=gnu99 -Iinclude -Wall -Werror=format-security -DSYSCONFDIR=\"/usr/local/etc\" -DVERSION=\"1.4-21-g017395f\"  -c -o src/sched.o src/sched.c
src/sched.c:34:17: error: redefinition of 'sigset' as different kind of symbol
static sigset_t sigset;
                ^
/usr/include/signal.h:103:8: note: previous definition is here
void    (*sigset(int, void (*)(int)))(int);
          ^
src/sched.c:91:18: warning: incompatible pointer types passing 'void (*(*)(int, void (*)(int)))(int)' to parameter of type 'sigset_t *' (aka 'struct __sigset *') [-Wincompatible-pointer-types]
        if (sigemptyset(&sigset) == -1) {
                        ^~~~~~~
/usr/include/signal.h:78:27: note: passing argument to parameter here
int     sigemptyset(sigset_t *);
                              ^
src/sched.c:100:2: warning: incompatible pointer types passing 'void (*(*)(int, void (*)(int)))(int)' to parameter of type 'sigset_t *' (aka 'struct __sigset *') [-Wincompatible-pointer-types]
        ADD_SIG(SIGTERM);
        ^~~~~~~~~~~~~~~~
src/sched.c:97:16: note: expanded from macro 'ADD_SIG'
        if (sigaddset(&sigset, _sig) == -1) { errorx("sigaddset(%d)", _sig); return 1; }
                      ^~~~~~~
/usr/include/signal.h:76:25: note: passing argument to parameter here
int     sigaddset(sigset_t *, int);
                            ^
src/sched.c:101:2: warning: incompatible pointer types passing 'void (*(*)(int, void (*)(int)))(int)' to parameter of type 'sigset_t *' (aka 'struct __sigset *') [-Wincompatible-pointer-types]
        ADD_SIG(SIGINT);
        ^~~~~~~~~~~~~~~
src/sched.c:97:16: note: expanded from macro 'ADD_SIG'
        if (sigaddset(&sigset, _sig) == -1) { errorx("sigaddset(%d)", _sig); return 1; }
                      ^~~~~~~
/usr/include/signal.h:76:25: note: passing argument to parameter here
int     sigaddset(sigset_t *, int);
                            ^
src/sched.c:104:2: warning: incompatible pointer types passing 'void (*(*)(int, void (*)(int)))(int)' to parameter of type 'sigset_t *' (aka 'struct __sigset *') [-Wincompatible-pointer-types]
        ADD_SIG(SIGALRM);
        ^~~~~~~~~~~~~~~~
src/sched.c:97:16: note: expanded from macro 'ADD_SIG'
        if (sigaddset(&sigset, _sig) == -1) { errorx("sigaddset(%d)", _sig); return 1; }
                      ^~~~~~~
/usr/include/signal.h:76:25: note: passing argument to parameter here
int     sigaddset(sigset_t *, int);
                            ^
src/sched.c:107:2: warning: incompatible pointer types passing 'void (*(*)(int, void (*)(int)))(int)' to parameter of type 'sigset_t *' (aka 'struct __sigset *') [-Wincompatible-pointer-types]
        ADD_SIG(SIGCHLD);
        ^~~~~~~~~~~~~~~~
src/sched.c:97:16: note: expanded from macro 'ADD_SIG'
        if (sigaddset(&sigset, _sig) == -1) { errorx("sigaddset(%d)", _sig); return 1; }
                      ^~~~~~~
/usr/include/signal.h:76:25: note: passing argument to parameter here
int     sigaddset(sigset_t *, int);
                            ^
src/sched.c:110:2: warning: incompatible pointer types passing 'void (*(*)(int, void (*)(int)))(int)' to parameter of type 'sigset_t *' (aka 'struct __sigset *') [-Wincompatible-pointer-types]
        ADD_SIG(SIGUSR1);
        ^~~~~~~~~~~~~~~~
src/sched.c:97:16: note: expanded from macro 'ADD_SIG'
        if (sigaddset(&sigset, _sig) == -1) { errorx("sigaddset(%d)", _sig); return 1; }
                      ^~~~~~~
/usr/include/signal.h:76:25: note: passing argument to parameter here
int     sigaddset(sigset_t *, int);
                            ^
src/sched.c:111:2: warning: incompatible pointer types passing 'void (*(*)(int, void (*)(int)))(int)' to parameter of type 'sigset_t *' (aka 'struct __sigset *') [-Wincompatible-pointer-types]
        ADD_SIG(SIGUSR2);
        ^~~~~~~~~~~~~~~~
src/sched.c:97:16: note: expanded from macro 'ADD_SIG'
        if (sigaddset(&sigset, _sig) == -1) { errorx("sigaddset(%d)", _sig); return 1; }
                      ^~~~~~~
/usr/include/signal.h:76:25: note: passing argument to parameter here
int     sigaddset(sigset_t *, int);
                            ^
src/sched.c:114:2: warning: incompatible pointer types passing 'void (*(*)(int, void (*)(int)))(int)' to parameter of type 'sigset_t *' (aka 'struct __sigset *') [-Wincompatible-pointer-types]
        ADD_SIG(SIGIO);
        ^~~~~~~~~~~~~~
src/sched.c:97:16: note: expanded from macro 'ADD_SIG'
        if (sigaddset(&sigset, _sig) == -1) { errorx("sigaddset(%d)", _sig); return 1; }
                      ^~~~~~~
/usr/include/signal.h:76:25: note: passing argument to parameter here
int     sigaddset(sigset_t *, int);
                            ^
src/sched.c:117:2: warning: incompatible pointer types passing 'void (*(*)(int, void (*)(int)))(int)' to parameter of type 'sigset_t *' (aka 'struct __sigset *') [-Wincompatible-pointer-types]
        ADD_SIG(SIGRTMIN);
        ^~~~~~~~~~~~~~~~~
src/sched.c:97:16: note: expanded from macro 'ADD_SIG'
        if (sigaddset(&sigset, _sig) == -1) { errorx("sigaddset(%d)", _sig); return 1; }
                      ^~~~~~~
/usr/include/signal.h:76:25: note: passing argument to parameter here
int     sigaddset(sigset_t *, int);
                            ^
src/sched.c:122:3: warning: incompatible pointer types passing 'void (*(*)(int, void (*)(int)))(int)' to parameter of type 'sigset_t *' (aka 'struct __sigset *') [-Wincompatible-pointer-types]
                ADD_SIG(sig);
                ^~~~~~~~~~~~
src/sched.c:97:16: note: expanded from macro 'ADD_SIG'
        if (sigaddset(&sigset, _sig) == -1) { errorx("sigaddset(%d)", _sig); return 1; }
                      ^~~~~~~
/usr/include/signal.h:76:25: note: passing argument to parameter here
int     sigaddset(sigset_t *, int);
                            ^
src/sched.c:128:31: warning: incompatible pointer types passing 'void (*(*)(int, void (*)(int)))(int)' to parameter of type 'const sigset_t *' (aka 'const struct __sigset *') [-Wincompatible-pointer-types]
        if (sigprocmask(SIG_SETMASK, &sigset, NULL) == -1) {
                                     ^~~~~~~
/usr/include/signal.h:82:49: note: passing argument to parameter here
int     sigprocmask(int, const sigset_t * __restrict, sigset_t * __restrict);
                                                    ^
src/sched.c:167:21: warning: incompatible pointer types passing 'void (*(*)(int, void (*)(int)))(int)' to parameter of type 'const sigset_t *' (aka 'const struct __sigset *') [-Wincompatible-pointer-types]
                sig = sigwaitinfo(&sigset, &siginfo);
                                  ^~~~~~~
/usr/include/signal.h:93:44: note: passing argument to parameter here
int     sigwaitinfo(const sigset_t * __restrict, siginfo_t * __restrict);
                                               ^
src/sched.c:197:35: error: no member named 'si_fd' in 'struct __siginfo'
                        bar_poll_readable(bar, siginfo.si_fd);
                                               ~~~~~~~ ^
src/sched.c:215:31: warning: incompatible pointer types passing 'void (*(*)(int, void (*)(int)))(int)' to parameter of type 'const sigset_t *' (aka 'const struct __sigset *') [-Wincompatible-pointer-types]
        if (sigprocmask(SIG_UNBLOCK, &sigset, NULL) == -1)
                                     ^~~~~~~
/usr/include/signal.h:82:49: note: passing argument to parameter here
int     sigprocmask(int, const sigset_t * __restrict, sigset_t * __restrict);
                                                    ^
13 warnings and 2 errors generated.
<builtin>: recipe for target 'src/sched.o' failed
gmake: *** [src/sched.o] Error 1


I didn't come up with a solution yet, but I'm looking into this right now and see how far I'll get. If you come up with a solution, I'd be happy to know, too, of course!

Thanks in advance, if I can anyhow give further information please ping me up - I'm happy to provide further information and testing.

Regards,

Armin

**Comment by vivien** [comment]
See #127.

**Pull request closed without merging**
