### PR TITLE
Global Color Settings

### PR DESCRIPTION
**Pull request by gerrard00**
I'm new to i3blocks, but I've enjoyed using it so far. The only issue that I've run into is that there doesn't seem to be a way to share colors between blocks. This PR aims to add support for global color settings that can be used by any block. 

I also went ahead and modified the battery and wifi scripts to support the new settings.

It seems to work well on my machine and I thought others might be interested in the functionality.

### CODE REVIEW

**Comment by bchretien** [comment]
:+1: Useful feature indeed, setting/updating consistent colors across blocks can be a bit cumbersome for now.

**Comment by vivien** [comment]
Hi @gerrard00, I just catch up with this PR... Thanks for the contribution! Your code looks good, but I'm hesitant to merge this since I'm working on a more generic approach, to support passing arbitrary properties to the block, so that such variable won't need to be hardcoded anymore.

**Comment by gerrard00** [comment]
Understood! Thanks for taking a look.

**Comment by vivien** [comment]
Your proposed configuration should now work as expected now that support for dynamic properties has been added! Just defined your global *color_foo` variables and access them with `$color_foo` from your scripts!

**Pull request closed without merging**
