### PR TITLE
POSIX Script Blocklets

### PR DESCRIPTION
**Pull request by Nycroth**
Update: I've got my final commit on this. If anyone runs i3blocks on BSD or any other POSIX, non-Linux feel free to tell me if something doesn't work.

### CODE REVIEW

**Comment by 8carlosf** [comment]
I was thinking about converting all the scripts I use to bash myself, Perl is not my thing..
Is awk really needed? It adds a dependency, it's not a problem for me, but it reminds me that we should have some line in the header (here you have names and licence) with dependencies (acpi, awk, every thing that doesn't come default in all linux systems).
P.S.: I rather have awk, I'm just making a point about dependencies and ease of use and debug for new or less experienced users

**Comment by Nycroth** [comment]
I know awk and sed are often not installed by default. It is likely possible to complete all the scripts using the core binaries (grep, cut, tr, sort, uniq, etc...) plus /bin/sh; I'm more than happy to convert to that. I just went for what I felt was simplest to read. The memory script was written entirely in awk and there were other occurrences also. Awk's ability grep|cut and perform floating point math in a single command makes it rather appealing.

I also left 1-2 occurrences of sed for a similar reason. I found rewriting these uses was going to become more complex than simply leaving them would be.

I'll give writing all scripts with [GNU Core Utils](https://en.wikipedia.org/wiki/GNU_Core_Utilities) only a try. Then I'll push up a commit so everyone can see what that looks like. I may not get to this today as I have a dinner to attend around 18:00 EDT.

**Comment by Nycroth** [comment]
Well, I'm left with two conclusions.
1) Nobody runs Linux on laptops.
2) Every Linux user using a laptop who has read this and my forum post is a prick.

Both suck. I'll have a laptop in September. I'll be back to work on this then.

**Comment by kb100** [comment]
@Nycroth What do you want laptop users to do? You want the output of what command? I like jasonwryan's script except my laptop doesn't have charge_full, it has charge_now, but now charge_full. I use energy_full and energy_now. Perhaps use jasonwryan's script but check if charge_full and charge_now exist, and if not then check if energy_full and energy_now exists, and if not error.

Don't worry about predicting how much time is left on the battery. Those scripts never work reliably because battery drainage is highly nonlinear and the nonlinearity depends on your laptop's specific hardware and age etc.. Acpi tells me I have 30 minutes left for 2 hours and then in a matter of 30 seconds it goes to 5% and then %0.

If this is going to be a core script it should just output the percentage, and make it red if that percentage is <= 10%. If a user wants something else, there are plenty of contributed battery scripts. There is no need to burden yourself with maximum functionality for the user who wants absolute minimal dependencies.

**Comment by Nycroth** [comment]
All I want to do is have some fun coding and documenting. Sure, using another dependency takes no time and almost no effort on my part. Why not use another library, another utility, another package. Someone else has already solved this problem. But what's the fun in that?

I'm not working on i3blocks to break new ground. I just like solving problems. I wanted to ensure that installing i3blocks required as few dependencies as possible. It kind of pisses me off every time I install something and it requires 10 other packages. You know it's only using 3-5% of the code in any of those. I also wanted the scripts to be as simple as possible and no simpler. No embedded colours, no Perl, no confusing code (a.k.a. magic).

Of course calculating the time left in the battery is impossible. You're predicting the future. Yet, most people prefer having a time remaining to understand the current drain on the battery. Something like 50% means nothing beyond noting that you are not plugged in. You need to see that percent over time to get a feel for how your battery is doing. Seeing 50% and 26 minutes means either your battery is old/bad or you are using some serious power and need to plug in or close something(s). Nobody banks on the time. It just gives a convenient metric to judge the state of the batty over time in a single glance.

Why I need the exact values is the same as needing the exact error message when troubleshooting a problem. So far, everyone keeps telling me things like 'blah' is named 'blag' or there's also 'foo'. That really doesn't help. It's as useful as, "Running the program doesn't work." or "I get an error when I click the button." Sure none of that is incorrect, but it abstracts what is really happening. What helps is an exact directory listing and the value contained in each of the files. Yes I don't need 80% of the information I get, but without it I cannot tell if I am making the best choices or not.

**Comment by kb100** [comment]
From https://www.kernel.org/doc/Documentation/power/power_supply_class.txt:

    ~ ~ ~ ~ ~ ~ ~  Charge/Energy/Capacity - how to not confuse  ~ ~ ~ ~ ~ ~ ~
    ~                                                                       ~
    ~ Because both "charge" (µAh) and "energy" (µWh) represents "capacity"  ~
    ~ of battery, this class distinguish these terms. Don't mix them!       ~
    ~                                                                       ~
    ~ CHARGE_* attributes represents capacity in µAh only.                  ~
    ~ ENERGY_* attributes represents capacity in µWh only.                  ~
    ~ CAPACITY attribute represents capacity in *percents*, from 0 to 100.  ~
    ~                                                                       ~
    ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~

After reading the documentation I get the feeling that none of the variables are guaranteed to exist, it depends on the user's driver. I would use these approximations for remaining battery capacity: CAPACITY, CHARGE_NOW/CHARGE_FULL, ENERGY_NOW/ENERGY_FULL, using later elements in the list as fallbacks. If none of the elements are computable, either error out or print nothing.

As for predicting time left, if the driver supports TIME_TO_EMPTY, use that directly. Else if the user has ACPI installed, use ACPI's time left indicator. Else you can poll CHARGE_NOW or ENERGY_NOW and store the results in a temporary file, using the data in the temporary file to compute approximate time left.

**Comment by Nycroth** [comment]
Wow, thank you for finding this documentation. I didn't even think to go looking for it. I'm an idiot.

**Comment by Nycroth** [comment]
Alright. Finally found some time after the start of the semester. So, these scripts should:
* Cover all basic script needs
* Be POSIX compliant

This means, there should be no dependancies beyond GNU coreutils, sed, awk, and Bash.

**Comment by Nycroth** [comment]
Closing and restarting this work in i3blocks-contrib. I want to make a set of scripts that are as OS agnostic and public domain. This was a good first attempt but most of these fail to work on BSD and I haven't even tried Solaris. Maybe one day they will be ready for the core.

**Pull request closed without merging**
